spring.application.name=warp-backend
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=500ms
spring.data.redis.connect-timeout=1000ms
spring.cache.type=redis

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URI}

application.short-url.secret=${SHORT_URL_SECRET}
application.domain.url=${APPLICATION_DOMAIN_URL}